package owasp

import (
	"fmt"
	"log"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/s9rA16Bf4/APKHunt/lib/colors"
	"github.com/s9rA16Bf4/APKHunt/lib/notify"
)

func InvestigateAutoGeneratedScreenshots(Files []string) {
	notify.StartSection("The Auto-Generated Screenshots protection")
	var countScreenShots = 0
	for _, sources_file := range Files {
		if filepath.Ext(sources_file) == ".java" {
			cmd_and_pkg_screenShots, err := exec.Command("grep", "-nr", "-e", "FLAG_SECURE", sources_file).CombinedOutput()
			if err != nil {
				//fmt.Println("- Auto-Generated Screenshots has not been observed")
			}
			cmd_and_pkg_screenShots_output := string(cmd_and_pkg_screenShots[:])
			if strings.Contains(cmd_and_pkg_screenShots_output, "FLAG_SECURE") {
				fmt.Printf("%s%s%s", colors.Brown, sources_file, colors.Reset)
				log.Println(cmd_and_pkg_screenShots_output)
				countScreenShots++
			}
		}
	}
	if int(countScreenShots) >= 0 {
		notify.QuickNote()
		log.Printf("    - It is recommended to set the FLAG_SECURE option to protect from Auto-Generated Screenshots issue. Please note that, When the application goes into background, a screenshot of the current activity is taken which may leak sensitive information.")

		notify.Reference()
		log.Printf("    - owasp MASVS: MSTG-STORAGE-9 | CWE-200: Exposure of Sensitive Information to an Unauthorized Actor")
		log.Printf("    - https://mobile-security.gitbook.io/masvs/security-requirements/0x07-v2-data_storage_and_privacy_requirements")
	}
}
