package OWASP

func Wrapper() {
	// OWASP MASVS - V2: Data Storage and Privacy Requirements
	InvestigateStorageNPrivacyRequiements()

	// MASVS V2 - MSTG-STORAGE-2 - SQLite Database
	InvestigateSQLDatabse()

	// MASVS V2 - MSTG-STORAGE-2 - Firebase Database
	InvestigateFireDatabse()

	// MASVS V2 - MSTG-STORAGE-2 - Realm Database
	InvestigateRealmDatabse()

	// MASVS V2 - MSTG-STORAGE-2 - Internal Storage
	InvestigateInternalStorage()

	// MASVS V2 - MSTG-STORAGE-2 - External Storage
	InvestigateExternalStorage()

	// MASVS V2 - MSTG-STORAGE-2 - Temporary File Creation
	InvestigateTemporaryFileCreation()

	// MASVS V2 - MSTG-PLATFORM-2 - Local Storage - Input Validation
	InvestigateLocalStorageInputValidation()

	// MASVS V2 - MSTG-STORAGE-3 - Logs for Sensitive Data
	InvestigateLogsForSensitiveData()

	// MASVS V2 - MSTG-STORAGE-4 - NotificationManager
	InvestigateNotificationManager()

	// MASVS V2 - MSTG-STORAGE-5 - Keyboard Cache
	InvestigateKeyboardCache()

	// MASVS V2 - MSTG-STORAGE-7 - Sensitive Data Disclosure Through the User Interface
	InvestigateSensitiveDataThroughUserInterface()

	// MASVS V2 - MSTG-STORAGE-8 - AndroidManifest file - Package allowBackup
	InvestigateAllowBackup()

	// MASVS V2 - MSTG-STORAGE-9 - Auto-Generated Screenshots
	InvestigateAutoGeneratedScreenshots()

	// MASVS V2 - MSTG-STORAGE-10 - Memory flush
	InvestigateMemoryFlush()

	// MASVS V2 - MSTG-STORAGE-10 - ClipboardManager
	InvestigateClipboardManager()

	// MASVS V2 - MSTG-STORAGE-14 - Hard-coded Information
	InvestigateHardcodedInformation()

	// MASVS V2 - MSTG-STORAGE-14 - Possible Hard-coded Keys/Tokens/Secrets
	InvestigateHardCodedSecrets()
}
