package owasp

func Wrapper(Files []string, ManifestPath string, ResourceFiles []string) {
	// MASVS V2 - MSTG-STORAGE-2 - SQLite Database
	InvestigateSQLDatabase(Files)

	// MASVS V2 - MSTG-STORAGE-2 - Shared Preferences
	InvestigateSharedPreferences(Files)

	// MASVS V2 - MSTG-STORAGE-2 - Firebase Database
	InvestigateFireDatabse(ResourceFiles)

	// MASVS V2 - MSTG-STORAGE-2 - Realm Database
	InvestigateRealmDatabse(Files)

	// MASVS V2 - MSTG-STORAGE-2 - Internal Storage
	InvestigateInternalStorage(Files)

	// MASVS V2 - MSTG-STORAGE-2 - External Storage
	InvestigateExternalStorage(Files)

	// MASVS V2 - MSTG-STORAGE-2 - Temporary File Creation
	InvestigateTemporaryFileCreation(Files)

	// MASVS V2 - MSTG-PLATFORM-2 - Local Storage - Input Validation
	InvestigateLocalStorageInputValidation(Files)

	// MASVS V2 - MSTG-STORAGE-3 - Logs for Sensitive Data
	InvestigateLogsForSensitiveData(Files)

	// MASVS V2 - MSTG-STORAGE-4 - NotificationManager
	InvestigateNotificationManager(Files)

	// MASVS V2 - MSTG-STORAGE-5 - Keyboard Cache
	InvestigateKeyboardCache(ResourceFiles)

	// MASVS V2 - MSTG-STORAGE-7 - Sensitive Data Disclosure Through the User Interface
	InvestigateSensitiveDataThroughUserInterface(ResourceFiles)

	// MASVS V2 - MSTG-STORAGE-8 - AndroidManifest file - Package allowBackup
	InvestigateAllowBackup(ManifestPath)

	// MASVS V2 - MSTG-STORAGE-9 - Auto-Generated Screenshots
	InvestigateAutoGeneratedScreenshots(Files)

	// MASVS V2 - MSTG-STORAGE-10 - Memory flush
	InvestigateMemoryFlush(Files)

	// MASVS V2 - MSTG-STORAGE-10 - ClipboardManager
	InvestigateClipboardManager(Files)

	// MASVS V2 - MSTG-STORAGE-14 - Hard-coded Information
	InvestigateHardcodedInformation(Files)

	// MASVS V2 - MSTG-STORAGE-14 - Possible Hard-coded Keys/Tokens/Secrets
	InvestigateHardCodedSecrets(ResourceFiles)
}
